os: linux
language: go

go:
  - '1.13.x'

install:
  - go get -u github.com/golang/lint/golint

script:
  - test -z "$(go fmt -s -l -w ./... | tee /dev/stderr)"
  - golint -set_exit_status ./...
  - go build -v ./...
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
